### ISSUE TITLE
Black screen after reboot on 0.48

### ISSUE THREAD

**Issue by tomqw** [ciscon/quake-bootable#4] opened 2024-01-28 15:53 UTC
After flashing image to SSD it boots properly only on the first time. After reboot there is black screen.
Version 0.48.0

It works properly on 0.47.0

After some troubleshooting it turns out that new version of plymouth package causing this issue.
v 0.48.0: 22.02.122-4
v 0.47.0: 24.004.60-1

**Comment by tomqw** [comment] 2024-01-28 15:57
Log from upgrading plymouth package
quakeuser@quakeboot:~$ sudo apt-get --only-upgrade install plymouth
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libplymouth5 plymouth-label
Suggested packages:
  desktop-base plymouth-themes
The following packages will be upgraded:
  libplymouth5 plymouth plymouth-label
3 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.
Need to get 282 kB of archives.
After this operation, 174 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://deb.debian.org/debian testing/main amd64 libplymouth5 amd64 24.004.60-1 [125 kB]
Get:2 https://deb.debian.org/debian testing/main amd64 plymouth-label amd64 24.004.60-1 [16.7 kB]
Get:3 https://deb.debian.org/debian testing/main amd64 plymouth amd64 24.004.60-1 [141 kB]
Fetched 282 kB in 0s (786 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 68423 files and directories currently installed.)
Preparing to unpack .../libplymouth5_24.004.60-1_amd64.deb ...
Unpacking libplymouth5:amd64 (24.004.60-1) over (22.02.122-4) ...
Preparing to unpack .../plymouth-label_24.004.60-1_amd64.deb ...
Unpacking plymouth-label (24.004.60-1) over (22.02.122-4) ...
Preparing to unpack .../plymouth_24.004.60-1_amd64.deb ...
Unpacking plymouth (24.004.60-1) over (22.02.122-4) ...
Setting up libplymouth5:amd64 (24.004.60-1) ...
Setting up plymouth (24.004.60-1) ...
update-initramfs: Generating /boot/initrd.img-6.5.0-5-amd64
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
Setting up plymouth-label (24.004.60-1) ...
Processing triggers for libc-bin (2.37-13) ...

**Comment by tomqw** [comment] 2024-01-28 16:22
After disabling plymouth by removing "splash" option from grub conf system boots properly.

**Comment by ciscon** [comment] 2024-01-28 18:43
interesting I'm not able to reproduce, i just booted version 48 and it does in fact have plymouth version 24, was anything done upon first boot?  i just booted it up, let everything settle, and did a cold reboot.

**Comment by tomqw** [comment] 2024-01-29 12:17
Nothing done on first reboot. When system boots for the first time I just type reboot-system in cmd and after that it no longer boots.
I'm going to try to troubleshoot it a bit.

**Comment by tomqw** [comment] 2024-01-30 23:50
I've tried Enabling KMS (NVIDIA Proprietary) from https://wiki.debian.org/plymouth by adding nvidia-drm.modeset=1 option to grub config file. It fixes the problem.

**Comment by ciscon** [comment] 2024-01-31 07:49
interesting, it's using the same module on boot both times so it's odd behavior changes, i'll enable kernel modesetting on the driver in the build regardless.

**Comment by ciscon** [comment] 2024-03-24 20:23
i'm closing this until we can get someone to reproduce it on a newer version

**Closed as completed by ciscon** 2024-03-24 20:23 UTC
